spring:
  application:
    name: ms-users


  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console


  security:
    oauth2:
     client:
       registration:
         keycloak:
           client-id: clienteFinal
           client-secret: coUBoeB784LJHydRicEV4vTvRxaWs1Z8
           authorization-grant-type: client_credentials
 #          redirect-uri: http://localhost:8082/login/oauth2/code/keycloak #http://localhost:9090/*
       provider:
         keycloak:
 #          issuer-uri: http://localhost:8080/realms/DH
           tokenUri: http://localhost:8080/realms/DH/protocol/openid-connect/token

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/DH


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #enabled: false

server:
  port: 8082

